version: '3.1'

services:

  db:
    container_name: idatabase
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: I5uSS1kn08
    ports:
      - 5433:5433
    env_file:
      - ".env"
#    network_mode: "host"

  adminer:
    container_name: iadminer
    image: adminer
    restart: always
    ports:
      - 8282:8282
#    network_mode: "host"

  tgbot:
    container_name: ibot
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"

